@startuml

/'SUBSYSTEMS'/
component ur5e_cell_moveit_config {
 }

  component moveit_config_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component bt_operator {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin bt_operator.start_application as "start_application" #green

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component moveit_skill_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component ur_io_control_gripper_skill_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component lifecycle_manager {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }


@enduml