moveit_skill_server:
  ros__parameters:
    use_sim_time: false
    plan_request_params_planning_pipeline: pilz_industrial_motion_planner
    plan_request_params_planner_id: PTP
    plan_request_params_planning_attempts: 10
    step_size: 0.005
    min_fraction: 0.5
    max_acceleration_scaling_factor: 0.1
    planning_time: 1.0
    planning_pipelines_pipeline_names: [ompl, pilz_industrial_motion_planner]
    planning_scene_monitor_options_name: planning_scene_monitor
    planning_scene_monitor_options_robot_description: robot_description
    planning_scene_monitor_options_joint_state_topic: /joint_states
    planning_scene_monitor_options_attached_collision_object_topic: /moveit_cpp/planning_scene_monitor
    planning_scene_monitor_options_publish_planning_scene_topic: /moveit_cpp/publish_planning_scene
    planning_scene_monitor_options_monitored_planning_scene_topic: /moveit_cpp/monitored_planning_scene
    planning_scene_monitor_options_wait_for_initial_state_timeout: 10.0
    moveit_simple_controller_manager_controller_names: [joint_trajectory_controller]
    moveit_simple_controller_joint_trajectory_controller_type: FollowJointTrajectory
    moveit_simple_controller_joint_trajectory_controller_action_ns: follow_joint_trajectory
    moveit_simple_controller_joint_trajectory_controller_default: true
    moveit_simple_controller_joint_trajectory_controller_joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
    wait_server_timeout_seconds: 10

